# The default 79 character limit is sometimes unproductive.
LineLength:
  Max: 100

# The default 10 lines limit is unrealistic.
MethodLength:
  Max: 15

Style/RegexpLiteral:
  Enabled: false

Encoding:
  Enabled: false
