inherit_from: .rubocop_todo.yml

Layout/IndentArray:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodMissing:
  Exclude:
    - spec/support/silence_output.rb

Style/RegexpLiteral:
  Exclude:
    - '**/*.gemspec'
    - '**/Guardfile'
